### ISSUE TITLE
19th April with Sion Whallens

### ISSUE THREAD

**Issue by jsms90** [InFact-coop/InFact#11]
### Wednesday 19th April, 5.30pm
You should all have received a google calendar invite.

@nogainbar Can you clarify roughly what we should expect from Wednesday? It's not the photography session, right? Just the first half of the email about giving advice?

Email from Sion:
> It was great to see you at ‘Freeing the Freelancers’ and I’m just following up on a couple of things, plus a new request.
>
> Perhaps I can visit you at F&C and we can talk in a group about your plans for a new coop, discuss how you can get good advice and support in the process. Wednesdays are generally good times for me, or any day in the late afternoon after 4.
>
> With my Calverts hat on, I am brokering some photography for Coops UK to use in their communications and we would like to get a set of professional photos of a tech coop. F&C would be ideal. We have a photographer in mind and would like to come to F&C for half a day when it’s convenient, hopefully would be minimal disruption. My colleague Rowan Powell (in cc) would art direct. We would propose to share rights to the resulting suite if pics between Coops UK, Calverts and F&C.

By the way, [this is Calverts](http://www.calverts.coop/)

See [this video](https://vimeo.com/162710674) to see Sion talking about Calverts

**Comment by nogainbar** [comment]
To clarify, the meeting on Wednesday is not for the photoshoot but Sion has offered to talk to us about starting a coop and answering any questions.. giving advice..

Also, he has mentioned to me a few schemes that we can apply to in order to get some mentorship about setting a co-op, he is currently mentoring a new formed co-op through those schemes so we can ask him about that too and see if we can get our feet in.

I would suggest that if there are any pressing questions that anyone wants to ask him, we can write them down here and refer to this issue during the meeting. :)

**Comment by jsms90** [comment]
Action Points:
+ Minutes are on the way - will be in a PR
+ Apply to The Hive, to pay for 2 days of Sion's time in assisting us
  + Write an application to The Hive
  + Send the draft to Sion to review
  + Send off
+ Apply to Bright Ideas
  + Research into the scheme
  + Draft application
  + Send
+ Define mission & vision statement (next meeting?)
+ Discuss pay scale & the difference between project types and sizes (next meeting?)
