### ISSUE TITLE
Agenda for meeting 2/5/17

### ISSUE THREAD

**Issue by nogainbar** [InFact-coop/InFact#32]
- NHS PROJECT: #22 
  - Decide who will lead the client liason with NHS project. 
  - team composition
  -  date and availability for leading June workshop

**Comment by bradreeder** [comment]
* Anna Freud Project (Team availability + composition, confirmation of budget.)
* Proposals for next steps: #30 & #31 (if there's time and we feel discussion online has matured enough.)

**Comment by emilyb7** [comment]
agree that we should discuss #30 and #31

**Comment by nogainbar** [comment]
- IDEO design thinking workshop- dates for weekly meeting that suit everyone from after im back from israel

**Comment by jsms90** [comment]
I found it pretty difficult to minute take for the discussion around #30 #31. I'm still not really sure what was decided on with regards to those issues. If anyone has a clearer understanding than me, please comment in those issues and/or close any that no longer need to stay open.

I put updates on the projects directly into those issues, since they are ongoing and can't be closed:
+ [Anna Freud](https://github.com/InFact-coop/InFact/issues/21#issuecomment-298716404)
+ [NHS project](https://github.com/InFact-coop/InFact/issues/22#issuecomment-298707017)
